version: "3.8"
services:
  builder-amd:
    container_name: ziloo-builder-amd
    build:
      context: .
      dockerfile: ./builder.Dockerfile
      # target: ziloo-builder-amd
    platform: "linux/amd64"
    tty: true
    volumes: 
    - .:/workspace
    - ./boards:/boards
  builder-arm64:
    container_name: ziloo-builder-arm64
    build:
      context: .
      dockerfile: ./builder.Dockerfile
      # target: ziloo-builder-arm64
    platform: "linux/aarch64"
    tty: true
    volumes: 
    - .:/workspace
    - ./boards:/boards


