version: "3.8"
services:
  builder-amd:
    container_name: ziloo-builder-amd
    image: ziloo/image-builder
    build:
      context: .
      dockerfile: ./device/builder.Dockerfile
      # target: ziloo-builder-amd
      target: base-repo-image
    platform: "linux/amd64"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
    - ./dist:/dist
    - ./device:/device
  builder-imx8:
    container_name: ziloo-builder-imx8
    image: ziloo/image-builder
    build:
      context: .
      dockerfile: ./device/builder-imx8.Dockerfile
      # target: ziloo-builder-amd
      target: base-repo-image
    platform: "linux/amd64"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
    - ./dist:/dist
    - ./device:/device
  builder-rv1109:
    container_name: ziloo-builder-rv1109
    image: ziloo/image-builder-rv1109
    build:
      context: .
      dockerfile: ./device/builder-rv1109.Dockerfile
    platform: "linux/amd64"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
    - ./dist:/dist
    - ./device:/device
  builder-rv1109-facial-gate:
    container_name: ziloo-builder-rv1109-facial-gate
    build:
      context: .
      dockerfile: ./device/builder-rockchip.Dockerfile
      target: rv1109-face-gate
    platform: "linux/amd64"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
    - ./dist/build/rv1109-facial-gate:/dist
    - ./device:/device
  builder-rv1126-facial-gate:
    container_name: ziloo-builder-rv1126-facial-gate
    build:
      context: .
      dockerfile: ./device/builder-rockchip.Dockerfile
      target: rv1126-face-gate
    platform: "linux/amd64"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
    - ./dist/build/rv1126-facial-gate:/dist
    - ./device:/device


  builder-rv1109-ai-uvc:
    container_name: ziloo-builder-rv1109-ai-uvc
    build:
      context: .
      dockerfile: ./device/builder-rockchip.Dockerfile
      target: rv1109-ai-uvc
    platform: "linux/amd64"
    #stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
    - ./dist/build/rv1109-ai-uvc:/dist
    - ./device:/device
  builder-rv1126-ai-uvc:
    container_name: ziloo-builder-rv1126-ai-uvc
    build:
      context: .
      dockerfile: ./device/builder-rockchip.Dockerfile
      target: rv1126-ai-uvc
    platform: "linux/amd64"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
    - ./dist/build/rv1126-ai-uvc:/dist
    - ./device:/device

  builder-arm64:
    container_name: ziloo-builder-arm64
    build:
      context: .
      dockerfile: ./device/builder.Dockerfile
      # target: ziloo-builder-arm64
    platform: "linux/aarch64"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
    - ./dist:/dist
    - ./device:/device

