version: '3'
services:
  ziloo-builder:
    container_name: ziloo-builder-user
    image: ziloo/image-builder-user
    platform: "linux/amd64"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    entrypoint: bash
    volumes: 
    - ./etc:/workspace/etc
    - ./dist:/workspace/dist
    - ./device/imx8:/workspace/device/imx8
    - ./mcuxsdk:/workspace/mcuxsdk
    - ./downloads:/workspace/downloads
    - ./cache:/workspace/build-ucm-imx8m-plus/cache
    - ./sstate-cache:/workspace/build-ucm-imx8m-plus/sstate-cache
    
