name: Publish Docker image

on:
  push:
    branches: [ main ]
    paths: 
      - etc/
      - .github/workflows
      - Dockerfile
      - .dockerignore
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ziloo/image-builder
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: 
            - ${{ steps.meta.outputs.tags }} 
            - latest
          labels: ${{ steps.meta.outputs.labels }}