name: TargetMCU

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the RP2040 branch
  push:
    branches: [ hw/imx8 ]
    paths:
      - 'device/imx8/**/*'
      - 'device/*'      
  pull_request:
    branches: [ hw/imx8 ]
    paths:
      - 'device/imx8/**/*'
      - 'device/*'      

jobs:
  build:
    runs-on: [self-hosted]
    container: ziloo/image-builder
    name: i.MX8 build running in Docker
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: create required directories
        run: |
          mkdir -p workspace

      
