name: remote runner workflow

on:
    push:
        branches: [ gunja/builder ]
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: run oneliner
              run: echo Hello world
            - name: multiliner
              run: |
                echo add another action
                ls -l
                pwd
            - name: create required directories
              run: |
                mkdir workspace
            - name: build base image
              run: docker build -f device/builder-all-in-one.Dockerfile -t base-repo-image --target base-repo-image .
              run: docker build -f device/builder-all-in-one.Dockerfile -t rv1109-ai-uvc-run --target rv1109-ai-uvc-run .
            - name: updating and building inside docker
              run: docker run -v ${PWD}:/workspace -v ${PWD}/dist/build/rv1109-ai-uvc:/dist rv1109-ai-uvc-run
            - uses: actions/download-artifact@v2
              with:
                name: rv1109-ai-uvc
                path: /dist
              
