name: remote runner workflow

on:
    push:
        branches: [ gunja/builder ]
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: run oneliner
              run: echo Hello world
            - name: multiliner
              run: |
                echo add another action
                ls -l
                pwd
            - name: create required directories
              run: |
                mkdir workspace
            - name: building base image
              run: docker build -f device/builder-all-in-one.Dockerfile -t base-repo-image --target base-repo-image .
            - name: building rv1109-ai-uvc-run image
              run: docker build -f device/builder-all-in-one.Dockerfile -t rv1109-ai-uvc-run --target rv1109-ai-uvc-run .
            - name: updating and building inside docker
              run: docker run --rm -v ${PWD}/dist/build/:/dist rv1109-ai-uvc-run
            - uses: actions/upload-artifact@v2
              with:
                name: rv1109-ai-uvc
                path: dist/build/rv1109-ai-uvc
            - uses: actions/upload-artifact@v2
              with:
                name: rv1109-facial-gate
                path: dist/build/rv1109-facial-gate
            - uses: actions/upload-artifact@v2
              with:
                name: rv1126-ai-uvc
                path: dist/build/rv1126-ai-uvc
            - uses: actions/upload-artifact@v2
              with:
                name: rv1126-facial-gate
                path: dist/build/rv1126-facial-gate
